Repository chainguard-dev/rumble, pull requests merged in 2023-04, with the labels that each got.

#37 Refresh comparable image list
  images.txt
Labels: enhancement

#38 Fix some tags in comparable images
  images.txt
Labels: bug

#44 Add partial list of official docker hub images
  images.txt
Labels: enhancement

#50 Add .chainguard file
  .chainguard/source.yaml
Labels: enhancement

#51 Add image build time to data
  .github/workflows/scan.yml
  cmd/tableinit/main.go
  go.mod
  go.sum
  main.go
  pkg/oci/oci.go
  pkg/types/csv.go
Labels: bug, enhancement

#53 Remove nextcloud:latest from images.txt
  images.txt
Labels: bug

#61 Add more dockerhub official images to images.txt
  images.txt
Labels: enhancement
